# Use a stable Debian as the base image
FROM localhost/codex

# My own set of tools
RUN apt-get install -y --no-install-recommends \
	gcc \
	cmake \
	ncat \
	php-cli \
	php-pgsql \
	php-sqlite3 \
	python3-full \
	python3-ipython \
	python3-virtualenv \
	python3-pip \
	python3-pytest \
	postgresql-client \
	sqlite3 \
	jq

# Clean-up
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 5173
